### ISSUE TITLE
connect ok but TCPServer couldn't receive any data

### ISSUE THREAD

**Issue by anruoran** [caichao/livestreamcsi#2]
Hello Mr Cai,
  I’m studying real-time display of csi, and your code has given me much help,thank you! But I'm still experiencing some problems. I would appreciate it if you could help me. The details are as follows.
  Because my matlab version is 2010b on ubuntu 11.04(ubuntu 11.04 is able to support the 802.11 tool after Tsinghua University‘s students made some changes), the program “realtime_plot.m” could only run after I make some changes for it. After I ran the program on matlab and ran "sudo ./log save.dat” on terminal, the terminal indicated connect ok and the file named save.dat could log csi, but the TCP server couldn’t receive any data(ValuesReceived and BytesAvailable is always 0). And whenever I stop the program by using Ctrl+C, matlab shows the stop position is in the line of “nBytes = get(TCPServer,'BytesAvailable');”
  I have tried to solve it but I failed. Could you give me some suggest ?  Thanks!
@caichao

**Comment by anruoran** [comment]
The program after I changed is as below.
 clc;clear all;
bufferLen = 393+2;%393+2 
echotcpip('on',1234)
TCPServer = tcpip('localhost',1234);% tcpip('localhost',1234,'NetworkRole','server')
set(TCPServer,'InputBufferSize',bufferLen);
% set(TCPServer,'Terminator','#');
set(TCPServer,'Timeout',10);
fopen(TCPServer);
carrier_frequency = 5.32*10^9;%5.32 2.412 2.437*10^9
channel_space =40*10^6/30;%20
antenna_space = 0.225;
sub_freq_delta = channel_space;
wrapped_packet_number = 2;
total_pks = [];
bk=10;
for j=1:bk
     while(1)
         nBytes = get(TCPServer,'BytesAvailable');
         if nBytes >= bufferLen
%             disp('read bytes ');disp(nBytes);
              break;
         end
     end
     i = i + 1;    
     x = linspace(1+i*N,N+i*N,N);    
     data = fread(TCPServer,nBytes,'uint8');
     flushinput(TCPServer);
     data = data(4:length(data));
     if length(data) == 392  % this means that we receive a valid package, if not parse the package will enconter error
         d = uint8(data);
         csi = read_bfee(d);         
%% To do something here
     end
end
fclose(TCPServer);
delete(TCPServer)
echotcpip('off')
disp('server closed');

**Comment by caichao** [comment]
Hope the following suggestions would help you:
(1)Print the some messages in the log.c program, make sure that csi data is actually streaming out. 
(2)Use some other tcp utilities to act as a server. For example, you can change the ip address in the log.c file and send the csi stream to another computer. 
(3)Make sure the tcp server is on before you try to log the csi.

**Comment by anruoran** [comment]
Thanks for your suggestions! It worked when I sent the csi stream to another computer. And I find the problem after I compared the matlab2010b on ubuntu 11.04 and matlab2014 on win10. It seems the matlab2010b couldn't support link 'localhost' as server, the "echotcpip('on',1234)"is for 'localhost'  as client.
